### PR TITLE
fix: style for smaller media

### LINKED ISSUE #492: Phone view crops sidebar menu
See screenshot

image

The leftbar menu now has an impossible to use scrollbar on phone view. Let's adapt it to look like the rightbar menu. See:

image

### PR DESCRIPTION
**Pull request by Revathyvenugopal162**
fix #492

### CODE REVIEW

File: src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/js/fuse_search.js
Comment (jorgepiloto) [inline src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/js/fuse_search.js:1]: We can discard the changes in this file.

File: src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/fuse-search.css [hunk 1]
```diff
@@ -166,3 +153,35 @@ html[data-theme="light"] .highlight {
...
+  align-items: center;
+  justify-content: center;
+  gap: 8px;
+  position: relative;
+  background-color: var(--ast-search-bar-enable-background);
+  border: 1px solid var(--ast-search-bar-enable-border);
+  height:40px;
+  width:300px;
+
+} */
```
Comment (jorgepiloto) [inline src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/fuse-search.css:187]: Maybe for another pull-request?

**Review by jorgepiloto — APPROVED** [review]
Everything working as expected. The sidebar is no longer cropped in small media. Thanks, @Revathyvenugopal162.
